name: Publish Docker image
on:
  push:
    branches: ['main']

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build -t diecoolenallgemeinenficker/bcaf-api:v1 .
      - name: publish
        run: |
          docker login -u diecoolenallgemeinenficker -p ${{ secrets.DOCKER_TOKEN }}
          docker push diecoolenallgemeinenficker/bcaf-api:v1